---
name: Cache Demo
on:
    push:
jobs:
    Cache-Demo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip     #It restores or saves cache
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }} #OS + hash = unique cache key
                restore-keys: |
                  ${{ runner.os }}-pip-
            #It will pick the most recent matching cache

