---
name: Docker Build
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v4
          - name: setup python
            uses: actions/setup-python@v5
            with:
                python-version: "3.11"
          - name: setup docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build the docker image
            run: docker build -t Dockerfile .
          - name: docker tag image
            run: docker tag simpe-app khirappawar/simpe-app:latest
            