---
name: Github-hosted runner
on:
        workflow_dispatch:

jobs: 
    ubuntu-os:
        runs-on: ubuntu-latest
        steps:
          - name: system info
            run: | 
              echo "OS: $(uname -a)"
              echo "Hostname: $(hostname)"
              echo "user: $(whoami)"


    windows-os:
      runs-on: windows-latest
      steps:
          - name: system info
            run: | 
                echo "OS: $env:OS"
                echo "Hostname: $env:COMPUTERNAME"
                echo "User: $env:USERNAME"
    macos-latest:
        runs-on: macos-latest
        steps:
            - name: system info
              run : |
                echo "OS: $(sw_vers -productName) $(sw_vers -productVersion)"
                echo "Hostname: $(hostname)"
                echo "User: $(whoami)"

