---
name: Job output
on:
    workflow_dispatch:

jobs:
    output-date:
        runs-on: ubuntu-latest
        outputs:
            today: ${{ steps.get-date.outputs.date }}
        steps:
          - name: Today's date
            id: get-date
            run: |
              DATE=$(date +%Y-%m-%d)
              echo "date=$(DATE)" >> $GITHUB_OUTPUT
    
    read-output:
        runs-on: ubuntu-latest
        needs: output-date
        steps:
            - name: Print the output date
              run: echo "Today's date is:${{needs.output-date.outputs.today}}"

              