---
name: Manual workflow triggers
"on":
  workflow_dispatch:
    inputs:
        environment:
            description: An enviroment passed from workflow
            required: true
            default: "staging"
            type: choice
            options: 
                - staging 
                - production
jobs:
  manual_run: 
    name: Manual workflow runs
    runs-on: ubuntu-latest
    steps: 
      - name: Running Environment
        run: echo "The selected environment is, ${{ github.event.inputs.environment }}"







