---
name: Multi-job workflow
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Building the app
              run: echo "Building the app"
    
    test:
        needs: build            #Runs only after build succeeds
        runs-on: ubuntu-latest
        steps:
            - name: Testing the app
              run: echo "Testing the code/application"
    deploy:
        needs: test             #Runs only test succeeds
        runs-on: ubuntu-latest
        steps:
            - name: Deploying the app
              run: echo "Deploying the app"
    
