---
name: PR validation workflow
on:
    pull_request:
      branches: [main]

jobs:
    file-size-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Fail if any PR more than 1 MB
              run: |
                large_files:$(find . -type f -size +1MB)
                if [ -n "$large_files" ]; then
                echo "Files larger than 1MB found:"
                echo "$large_files"
                exit 1
                else
                echo "All files under 1MB"
                fi
    branch-name-check:
        runs-on: ubuntu-latest
        steps:
          - name: Read the branch name
            run: |
              BRANCH=${{ github.head_ref }}
              echo "Branch is: $BRANCH"
              if [[ "$BRANCH" =~ ^(feature/|fix/|docs/).* ]]; then
               echo "Branch naming convention valid"
              else
               echo "Invalid branch name"
               exit 1
              fi

    pr-body-check:
        runs-on: ubuntu-latest
        steps:
            - name: Read the PR body
              run: |
                BODY="${{ github.event.pull_request.body }}"
                if [ -z "$BODY" ]; then
                echo "Waring PR body is missing"
                else
                echo "PR description present"
                fi
