---
name: Pyhton script
on:
    workflow_dispatch:
jobs:
    python-script:
        runs-on: ubunut:latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: Setup pyhton
              uses: actions/steup-python@v5
              with:
                pyhton version: '3.x'
            - name: Install dependencies
              run: |
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run script
              run: python script.py
