---
name: My Secret variable
on:
    push:
        branches: [main]

jobs:
    my_secret-job:
        runs-on: ubuntu:latest
        env:
            Secret_message: ${{ secrets.MY_SECRET_MESSAGE }}
        steps:
          - name: use the secret variables
            run: |
              if [ -n "${{ secrets.MY_SECRET_MESSAGE }}"]; then
              echo "secret key is set: true"
              else
              echo "secret key is set: false"
              fi
