name: smart triggers

on:
  push:
    paths:
      - 'src/**'
      - 'app/**'

jobs:
 
  print:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: print
        run: |
          Files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $Files; do
            echo "$file"
          done